# Generated by Django 4.0 on 2022-01-02 16:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
