# Generated by Django 4.0.1 on 2022-01-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_ad_remove_comment_reply_comment_post_comment_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/article-main'),
        ),
    ]
