# Generated by Django 4.0.1 on 2022-01-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_category_remove_comment_replies_comment_replied_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publishDate',
            new_name='publish_date',
        ),
        migrations.AlterField(
            model_name='ad',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
