# Generated by Django 4.0.1 on 2022-01-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_alter_comment_replied_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='posts', to='News.Category'),
        ),
    ]
