# Generated by Django 4.0.1 on 2022-01-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0010_rename_category_post_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url_name',
            new_name='eng_name',
        ),
    ]
