# Generated by Django 4.0.1 on 2022-01-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0011_rename_url_name_category_eng_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replied_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='News.comment'),
        ),
    ]
